apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: webhook-server
webhooks:
  - name: webhook-server.default.svc.cluster.local
    admissionReviewVersions:
      - "v1beta1"
    sideEffects: "None"
    timeoutSeconds: 30
    objectSelector:
      matchLabels:
        webhook-server-enabled: "true"
    clientConfig:
      service:
        name: webhook-server
        namespace: default
        path: "/mutate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURiRENDQWxRQ0NRRElkVHM0VTMzWTNqQU5CZ2txaGtpRzl3MEJBUXNGQURCM01Sb3dHQVlEVlFRRERCRjMKWldKb2IyOXJMWE5sY25abGNpNWpZVEViTUJrR0ExVUVDd3dTVFhrdFEyOXljRzl5WVhSbExVZHliM1Z3TVJBdwpEZ1lEVlFRS0RBZE5lUzFEYjNKd01ROHdEUVlEVlFRSERBWlRlV1J1WlhreEREQUtCZ05WQkFnTUEwNVRWekVMCk1Ba0dBMVVFQmhNQ1FWVXdJQmNOTWpFd056RXlNVEl3TURRNVdoZ1BNakV5TVRBMk1UZ3hNakF3TkRsYU1IY3gKR2pBWUJnTlZCQU1NRVhkbFltaHZiMnN0YzJWeWRtVnlMbU5oTVJzd0dRWURWUVFMREJKTmVTMURiM0p3YjNKaApkR1V0UjNKdmRYQXhFREFPQmdOVkJBb01CMDE1TFVOdmNuQXhEekFOQmdOVkJBY01CbE41Wkc1bGVURU1NQW9HCkExVUVDQXdEVGxOWE1Rc3dDUVlEVlFRR0V3SkJWVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBTTZOamNzbzJ5ZUx1c1BFRzlaOUpvZ0hEOHNpSjdrTHhFb3I3bG1MZ2ppQnR3a0tNMHRYRWcxNgpyQVZEUzRHTVlBTHhWb3hQOHFVZHlRbWtJZHlka0lOTHQ1MzFFRFhQQXYyVzhoaDBRY29XM21ZRTIzRTdqMzJFCnExanhaOTBhSFJQZDFNWVlTYTU4YnphSEJKUE9ucVJvbDdIcHlCelM2eEI1SzJjVjJaa3dLazRMTkhDOVhYK0sKR2Z5azcwQmJvTHdFOHJ1RUI0RmdNc2VyQXBQLzN0SldZRFpIdUJHWVlraW5nUlNBSm42SGZnaC8xTXJ0UXZnSgpEbnNsR3E0VlNPcG1tV1BYWVRVNXBuTWl6N2RBM0YvNmV6K2VmMXBhVndKaGdaWElWbEJpZ1ZLVmU5NXc2MDlNCjRwU3FNV2owc2F2b2ljV2lWRVRRakZFeWVtamVKbmNDQXdFQUFUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUEKQ3UzcVlYK2JnWm5DbHA3QnpTMzZIQXIrZWllVnZPOVJQQnM1NkIzUDBVbnh2RDJNU3daL0pleWY5RWI3UUk4LwpMbXlrbFc1OEJWMjUvaXBEdWN4WGFMZjZqZXBMcFBzdi91QmRsOEt4VXl2Z21FNm1aN2JVMUFyRU9YVXBBMHVrCmwyaU9SY2EvZG1qVGJIblNvZE1LSFFqeW00a2o1NmpQMjFXVXRjcUxjL0J0bTZLd2t3ZmNDOVgzNnNkWmtDOTMKK0RxeXBQM1huR2xCM0JVaDgrWDNQeEdUVVFMMUpYNUJ0Mk8zV0lBdWJRVGxsRzdhYmV1R2h6QzloWTF5bGRHMQpIUldMUjRHempTMnRINzEzL0c3UGhEZmNSelZCdHBMaW9HTHlraDBkK2s3K1lUdjU5aDlkK3JweGJCdnRrWjZOCk9iVEs5a0F4TFBBT0tFSTUrT3dzU0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]