apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook-server
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhook-server
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webhook-server
subjects:
- kind: ServiceAccount
  name: webhook-server
  namespace: default
roleRef:
  kind: ClusterRole
  name: webhook-server
  apiGroup: rbac.authorization.k8s.io